require SQLAlchemy 1.4+
  File "/home/statbot/repo/statbot/sql.py", line 354, in __init__
    if not inspect(self.db).has_table("messages"):
AttributeError: 'PGInspector' object has no attribute 'has_table'